### ISSUE TITLE
Browser with countermeasures: Brave Browser

### ISSUE THREAD

**Issue by HACKE-RC** [gautamkrishnar/nothing-private#116]
Brave Browser : https://brave.com

All Versions Are Private

Windows/Linux/MacOs/Android

As a user, access to your web activity and data is sold to the highest bidder. Internet giants grow rich, while publishers go out of business. And the entire system is rife with ad fraud.

Brave Shields for Privacy

Block data-grabbing ads and trackers

The vast bulk of websites and ads include software that tries to identify you. They want to track your every move across the web. Brave blocks all this, allowing you to browse freely.

**Comment by KarthikNayak024** [comment]
What is this issue? I didn't understand.

**Comment by gautamkrishnar** [comment]
@KarthikNayak024 you should test that the https://www.nothingprivate.ml/ is not able to fingerprint the brave browser by running it. If https://www.nothingprivate.ml/ is not able to remember your name on incognito/private browsing mode in brave please open a pull request that adds brave browser to the list: https://github.com/gautamkrishnar/nothing-private/blob/master/browsers-with-countermeasures/README.md

**Comment by HACKE-RC** [comment]
Yes it was not able to detect my name

**Comment by D-10001** [comment]
I’m on IOS (Jailbroken) and It’s can track me with brave .

**Comment by Frediflexta** [comment]
Hi guys, I am not entirely sure if this issue is the same as what I want to raise now. 
So I tried following the steps on my brave browser, but then when I was asked to open on a private browser window, I used a private window with Tor. I never got past this first page, It kept trying to verify if I am human.

![Screenshot 2020-09-10 at 01 06 54](https://user-images.githubusercontent.com/26186206/92666982-a1e75d00-f302-11ea-9398-9d03c1f8ff6e.png)
