### ISSUE TITLE
Forget Me button not working

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/nothing-private#35]
*Forget Me* button is not working for "nothing private" web app.

### How to fix
* Please comment on this issue if you are working on it and let others know about it.
* You can find the server files here: https://github.com/gautamkrishnar/nothing-private/tree/master/db_server
* Make necessary changes
* Submit a PR

**Comment by floppypanda** [comment]
I am able to replicate this issue when using http://belikebill.azurewebsites.net/areyousafe as the base URL for the AJAX requests within main.js. When I run an instance of the Nothing Private server on my local machine, however, the "Forget Me" button works as intended. For context, I was able to run a private instance by executing "php -S localhost:3030" after changing the base URL accordingly. 

It appears to me that the bug is not occurring due to an inherent flaw in the forgetme.php code, but that there are issues with the PHP environment  or sqlite database on the public server. The following description may give insight into these issues.

On the browser side, the forgetme() JavaScript function fails due to a JSON parsing error:

_"Uncaught SyntaxError: Unexpected end of JSON input 
    at JSON.parse (<anonymous>) 
    at XMLHttpRequest.xhf.onreadystatechange."_

This JSON parsing error occurs because the public server returns an empty response to the forgetme() AJAX request. My hypothesis is that the execution of the SQL statement at forgetme.php:12 fails resulting in the if having a false condition at forgetme.php:15. Perhaps a quick check in the public server's error logs will reveal that this or some other issue with the server environment is the origin of this problem.

**Comment by gautamkrishnar** [comment]
@floppypanda thanks for your valuable input. I will look into it. :smile:

**Comment by gautamkrishnar** [comment]
It is working fine for me on linux. I encountered the bug when I was using the app in Safari  web browser in mac.
